// Start a static server at project root, then run with Playwright installed.
// PLAYWRIGHT_MODULE can point to a shared Playwright package; screenshots go to /tmp.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:process.env.INQUIRY_BROWSER_CHANNEL || 'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 if (process.env.INQUIRY_OFFLINE === '1') await page.context().setOffline(true);
 page.setDefaultTimeout(8000);
 const errors=[],failed=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message)); page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 page.on('response',r=>{if(r.status()>=400)failed.push(`${r.status()} ${r.url()}`)});
 const ok=name=>{checks.push(name);console.log('PASS',name)};
 await page.goto(`${process.env.INQUIRY_BASE_URL || 'http://127.0.0.1:8765/'}#lily/messages`);
 assert.equal(await page.locator('[data-inquiry-channel]').count(),3);
 assert.equal(await page.locator('.inquiry-item').count(),2);
 assert.equal(await page.locator('#inquiryMediaButton').isVisible(),false);
 await page.fill('#inquiryReplyInput','邮件草稿');
 await page.click('[data-inquiry-channel="whatsapp"]');
 assert.equal(await page.locator('#inquiryAccountSelect option').count(),2);
 assert.equal(await page.locator('#inquiryChatName').innerText(),'Mia Thompson');
 assert.equal(await page.locator('#inquiryReplyInput').inputValue(),'');
 await page.fill('#inquiryReplyInput','John 的独立草稿');
 await page.locator('#inquiryFileInput').setInputFiles({name:'quotation.txt',mimeType:'text/plain',buffer:Buffer.from('Quotation #100: USD 1200')});
 await page.selectOption('#inquiryAccountSelect','wa-elsa');
 assert.equal(await page.locator('#inquiryChatName').innerText(),'Mark Jensen');
 assert.equal(await page.locator('#inquiryReplyInput').inputValue(),'');
 assert.equal(await page.locator('#inquiryAttachmentList').isVisible(),false);
 await page.fill('#inquiryReplyInput','Elsa draft');
 await page.click('#inquiryAiTrigger');await page.waitForSelector('#inquiryAiText:not([hidden])');assert.match(await page.locator('#inquiryAiText').innerText(),/Elsa$/);await page.click('#inquiryAiClose');
 await page.selectOption('#inquiryAccountSelect','wa-john');
 assert.equal(await page.locator('#inquiryReplyInput').inputValue(),'John 的独立草稿');
 assert.match(await page.locator('#inquiryAttachmentList').innerText(),/quotation/);
 await page.click('#inquirySendReply');
 assert.match(await page.locator('#inquiryChatThread').innerText(),/本地演示/);
 const downloadPromise=page.waitForEvent('download'); await page.locator('#inquiryChatThread a[download]').click();
 const download=await downloadPromise; assert.equal(download.suggestedFilename(),'quotation.txt');
 const fs=require('node:fs');assert.equal(fs.readFileSync(await download.path(),'utf8'),'Quotation #100: USD 1200');
 ok('渠道与账号隔离、草稿及附件保留、文件发送与下载');
 // Actual image blob and modal preview.
 const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=320;canvas.height=180;const ctx=canvas.getContext('2d');ctx.fillStyle='#d7e9ff';ctx.fillRect(0,0,320,180);ctx.fillStyle='#304dd4';ctx.font='24px sans-serif';ctx.fillText('Product preview',30,95);return canvas.toDataURL('image/png').split(',')[1]});
 await page.locator('#inquiryMediaInput').setInputFiles({name:'product.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
 assert.equal(await page.locator('#inquiryAttachmentList img').count(),1);
 await page.click('#inquirySendReply'); await page.click('.inquiry-image-button');
 assert.equal(await page.locator('#inquiryMediaDialog').isVisible(),true);
 assert.equal(await page.locator('#inquiryMediaPreview').evaluate(i=>i.complete && i.naturalWidth>0),true);
 await page.keyboard.press('Escape'); assert.equal(await page.locator('#inquiryMediaDialog').isVisible(),false);
 // Record a small real playable video entirely inside the test browser.
 const video=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=160;canvas.height=90;const ctx=canvas.getContext('2d');const stream=canvas.captureStream(10);const recorder=new MediaRecorder(stream,{mimeType:'video/webm'});const chunks=[];const blob=await new Promise(resolve=>{recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>resolve(new Blob(chunks,{type:'video/webm'}));recorder.start();let n=0;const timer=setInterval(()=>{ctx.fillStyle=n%2?'#645bff':'#d1e7ff';ctx.fillRect(0,0,160,90);if(++n===5){clearInterval(timer);recorder.stop();stream.getTracks().forEach(t=>t.stop());}},100)});return Array.from(new Uint8Array(await blob.arrayBuffer()))});
 await page.locator('#inquiryMediaInput').setInputFiles({name:'product.webm',mimeType:'video/webm',buffer:Buffer.from(video)});
 await page.click('#inquirySendReply');
 await page.locator('#inquiryChatThread video').evaluate(async v=>{await v.play();v.pause()});
 assert.equal(await page.locator('#inquiryChatThread video').evaluate(v=>v.error===null && v.videoWidth===160),true);
 ok('图片发送、放大预览、视频发送和真实播放');
 await page.locator('#inquiryMediaInput').setInputFiles({name:'wrong.txt',mimeType:'text/plain',buffer:Buffer.from('invalid')});
 assert.match(await page.locator('#toast').innerText(),/不支持此媒体类型/);
 await page.locator('#inquiryFileInput').setInputFiles({name:'empty.txt',mimeType:'text/plain',buffer:Buffer.alloc(0)});
 assert.match(await page.locator('#toast').innerText(),/非空/);
 await page.locator('#inquiryFileInput').setInputFiles({name:'too-large.bin',mimeType:'application/octet-stream',buffer:Buffer.alloc(25*1024*1024+1)});
 assert.match(await page.locator('#toast').innerText(),/25 MB/);
 await page.locator('#inquiryFileInput').setInputFiles(Array.from({length:11},(_,i)=>({name:`file-${i}.txt`,mimeType:'text/plain',buffer:Buffer.from('a')})));
 assert.equal(await page.locator('.inquiry-attachment-chip').count(),10);
 for(let i=0;i<10;i++)await page.locator('[data-remove-inquiry-attachment]').first().click();
 assert.equal(await page.locator('#inquirySendReply').isDisabled(),true);
 ok('附件类型、空文件、25 MB、10 个上限及删除校验');
 await page.click('#inquiryFindContacts');
 await page.fill('#inquiryContactSearch','447700900215'); assert.equal(await page.locator('.inquiry-contact-row').count(),1);
 await page.click('.inquiry-contact-row'); assert.equal(await page.locator('.inquiry-item').count(),2);
 await page.click('#inquiryFindContacts');await page.fill('#inquiryContactSearch','not-present');assert.equal(await page.locator('.inquiry-contact-row').count(),0);
 await page.fill('#inquiryContactSearch','Atlas');await page.click('.inquiry-contact-row');
 assert.equal(await page.locator('#inquiryChatName').innerText(),'Sophie Chen');
 assert.match(await page.locator('#inquiryCompanyBody').innerText(),/Atlas Logistics/);
 assert.equal(await page.locator('.inquiry-item').count(),3);
 ok('联系人号码/公司搜索、空态、新会话和去重');
 await page.click('#inquiryCreateGroup'); assert.equal(await page.locator('#inquiryConfirmGroup').isDisabled(),true);
 await page.fill('#inquiryGroupName','   ');await page.click('[data-contact-id="mia"]');await page.click('[data-contact-id="james"]');
 assert.equal(await page.locator('#inquiryConfirmGroup').isDisabled(),true);
 await page.fill('#inquiryGroupName','采购协作组');await page.fill('#inquiryContactSearch','Sophie');
 assert.match(await page.locator('#inquiryGroupSelected').innerText(),/已选 2 人/);
 await page.click('#inquiryConfirmGroup');assert.equal(await page.locator('#inquiryChatName').innerText(),'采购协作组');
 assert.match(await page.locator('#inquiryCompanyBody').innerText(),/3 位成员/);
 await page.fill('#inquiryReplyInput','请确认交期');await page.press('#inquiryReplyInput','Control+Enter');
 assert.match(await page.locator('#inquiryChatThread').innerText(),/请确认交期/);
 ok('建群校验、跨搜索保留成员选择、群成员资料和群聊发送');
 await page.click('[data-inquiry-channel="whatsapp-business"]');assert.equal(await page.locator('#inquiryAccountSelect option').count(),2);
 await page.click('#inquiryCreateGroup');await page.fill('#inquiryGroupName','企业销售讨论组');
 await page.click('[data-contact-id="ava-business"]');await page.click('[data-contact-id="carlos"]');await page.click('#inquiryConfirmGroup');
 await page.locator('#inquiryMediaInput').setInputFiles({name:'business-product.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
 await page.click('#inquirySendReply');assert.equal(await page.locator('.inquiry-image-button').count(),1);
 await page.selectOption('#inquiryAccountSelect','wab-service');assert.equal(await page.locator('#inquiryChatName').innerText(),'Leo Park');
 await page.click('#inquiryFindContacts');assert.equal(await page.locator('.inquiry-contact-row').count(),2);await page.keyboard.press('Escape');
 ok('企业号多账号、独立联系人、建群与媒体消息');
 await page.click('[data-inquiry-channel="email"]');assert.equal(await page.locator('#inquiryReplyInput').inputValue(),'邮件草稿');
 assert.equal(await page.locator('#inquiryThreadContext').isVisible(),true);
 await page.click('[data-inquiry-file="chris-file-1"]');assert.match(await page.locator('#toast').innerText(),/示例附件/);
 await page.click('#inquiryAiTrigger');await page.waitForSelector('#inquiryAiText:not([hidden])');await page.click('#inquiryAiApply');assert.match(await page.locator('#inquiryReplyInput').inputValue(),/邮件草稿/);
 ok('邮件回复、主题、历史附件说明和 AI 润色回归');
 // Empty account must not retain previous account content.
 await page.evaluate(()=>{for(let i=inquiryDemoConversations.length-1;i>=0;i--)if(inquiryDemoConversations[i].accountId==='wab-service')inquiryDemoConversations.splice(i,1)});
 await page.click('[data-inquiry-channel="whatsapp-business"]');assert.equal(await page.locator('#inquiryChatEmpty').isVisible(),true);
 assert.equal(await page.locator('#inquiryChat').isVisible(),false);assert.equal(await page.locator('#inquiryCompanyPanel').isVisible(),false);
 ok('无会话账号空态，不残留其他账号内容');
 for(const [width,height] of [[1440,1000],[820,1180],[390,844],[360,740]]){
  await page.setViewportSize({width,height});await page.click('[data-inquiry-channel="whatsapp"]');await page.selectOption('#inquiryAccountSelect','wa-john');
  await page.screenshot({path:`/tmp/inquiry-${width}-list.png`,fullPage:true});
  await page.locator('[data-inquiry-id="mia-whatsapp"]').click();
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`overflow ${width}`);
  const top=await page.locator('.inquiry-channel-tabs').boundingBox();assert.ok(top.y >= 0, `channel navigation hidden ${width}`);
  const send=await page.locator('#inquirySendReply').boundingBox();assert.ok(send.y+send.height<=height,`send button clipped ${width}`);
  await page.screenshot({path:`/tmp/inquiry-${width}-chat.png`,fullPage:true});
  await page.click('#inquiryCompanyToggle');
  if(width<=720){await page.click('#inquiryCompanyMobileBack');await page.click('#inquiryMobileBack');assert.equal(await page.locator('#inquiryConversationList').isVisible(),true)}
  await page.click('#inquiryCreateGroup');await page.screenshot({path:`/tmp/inquiry-${width}-group.png`,fullPage:true});
  await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'inquiryCreateGroup');
  ok(`${width}px 布局、输入区、资料返回、弹窗焦点恢复`);
 }
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 const resources=await page.evaluate(async()=>{await document.fonts.ready;return {images:[...document.querySelectorAll('img')].filter(i=>i.getClientRects().length&&(!i.complete||!i.naturalWidth)).map(i=>i.src),icons:document.querySelectorAll('#lilyInquiryPage svg').length,fonts:document.fonts.status}});
 assert.deepEqual(resources.images,[]);assert.ok(resources.icons>0);assert.equal(resources.fonts,'loaded');
 ok('控制台无错误、无失败请求、可见图片/字体/图标加载正常');
 console.log(JSON.stringify({checks,errors,failed,resources},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
